/**
 * Generated Supabase database types.
 *
 * This file is regenerated by `pnpm db:types` after every migration.
 * Do not hand-edit. Until the first migrations land it is a placeholder.
 */
export type Json = string | number | boolean | null | { [key: string]: Json | undefined } | Json[];

export interface Database {
  public: {
    Tables: Record<string, never>;
    Views: Record<string, never>;
    Functions: Record<string, never>;
    Enums: Record<string, never>;
    CompositeTypes: Record<string, never>;
  };
}
